-- Add human_summary column to events table for plain-English translations
-- This will dramatically improve user comprehension and retention

ALTER TABLE public.events 
ADD COLUMN IF NOT EXISTS human_summary TEXT;

-- Add index for faster queries when filtering by human_summary
CREATE INDEX IF NOT EXISTS idx_events_human_summary 
ON public.events(human_summary) 
WHERE human_summary IS NOT NULL;

-- Add comment explaining the column
COMMENT ON COLUMN public.events.human_summary IS 
'Plain-English translation of the event that explains what happened and why it matters. Auto-generated by AI.';

-- Update RLS policies to include human_summary in select
-- (Existing policies should already cover this, but being explicit)
